project_id = "dspspshgnointeqxgnrw"

[functions.process-email-queue]
verify_jwt = true

[functions.send-transactional-email]
verify_jwt = true

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false

[functions.create-course-payment]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-course-reminders]
verify_jwt = false

[functions.add-to-waitlist]
verify_jwt = false

[functions.parse-course-photo]
verify_jwt = true

[functions.ical-feed]
verify_jwt = false

[functions.move-booking-participant]
verify_jwt = true

[functions.sync-course-to-gcal]
verify_jwt = false

[functions.admin-add-participant]
verify_jwt = true